import { Inter } from "next/font/google";
import Link from "next/link";
import "../assets/css/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="nav">
          <div className="logo">Logo</div>
          <div className="nav_menu">
            <Link href="/">
              <div>home</div>
            </Link>
            <Link href="/blog">
              <div>blog</div>
            </Link>
          </div>
        </div>
        <div className="page_body">{children}</div>
      </body>
    </html>
  );
}
